name: Trivy Terraform Security Scan
on: [push, pull_request]

permissions:
  actions: read
  security-events: write

jobs:
  terraform_security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      
      - name: Scan Terraform  
        uses: aquasecurity/trivy-action@0.29.0
        with:  
          scan-type: 'fs'  
          scan-ref: './terraform'  # Path to your Terraform files  
          format: 'sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'  
          exit-code: 0
          output: 'trivy-terraform-results.sarif'  

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: 'trivy-terraform-results.sarif'
  